name: kulobal
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  build_runner: ^2.4.8
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.1
  country_picker: ^2.0.25
  cupertino_icons: ^1.0.6
  dio: ^5.3.4
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^3.1.0
  flutter_cache_manager: ^3.3.1
  flutter_local_notifications: ^17.1.2
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.9
  go_router: ^13.0.1
  gradient_borders: ^1.0.1
  image_cropper: ^7.0.5
  image_picker: ^1.1.2
  intl: ^0.18.1
  intl_phone_field: ^3.2.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  pin_code_fields: ^8.0.1
  riverpod_annotation: ^2.2.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  velocity_x: ^4.1.2
  uuid:
  youtube_player_flutter: ^9.0.1
  path_provider: ^2.1.3
  timezone: ^0.9.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.3.5

flutter:
  uses-material-design: true

  fonts:
    - family: Eu
      fonts:
        - asset: assets/font/Euclid Circular B Regular.ttf

    - family: Eubold
      fonts:
        - asset: assets/font/Euclid Circular B Bold.ttf

    - family: Eumed
      fonts:
        - asset: assets/font/Euclid Circular B SemiBold.ttf

  assets:
    - assets/
    - assets/logo/
    - assets/icons/
